[build]
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=lld", "-Zthreads=16"]
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=lld", "-Zthreads=16"]
